services:
  postgresql:
    image:
      postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
        POSTGRES_DB: testeDb
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: teste123